#pragma once

#include "../painter/painter_2_1_draw_bg.h"
#include "../painter/painter_2_2_draw_point.h"
#include "../painter/painter_2_5_draw_triangle.h"
#include "../painter/painter_2_6_draw_triangle_ani.h"
#include "../painter/painter_4_1_draw_cube.h"
#include "../painter/painter_4_2_draw_cube_instanced.h"
#include "../painter/painter_4_3_draw_cube_pyramid.h"
#include "../painter/painter_4_4_draw_planet.h"
#include "../painter/painter_5_1_draw_pyramid_texture.h"
#include "../painter/painter_6_1_draw_sphere.h"
#include "../painter/painter_6_2_draw_torus.h"
#include "../painter/painter_6_3_draw_model.h"
#include "../painter/painter_7_1_draw_torus_gold_gouraud.h"
#include "../painter/painter_7_2_draw_torus_gold_phong.h"
#include "../painter/painter_7_3_draw_torus_gold_blinn_phong.h"
#include "../painter/painter_8_1_draw_shadow.h"